---
httpd_site_url: "https://www.tooplate.com/zip-templates/2152_event_invitation.zip"
httpd_site_zip: "/tmp/2152_event_invitation.zip"
httpd_site_dir: "/tmp/2152_event_invitation"
httpd_web_root: "/var/www/html"
